name: Claude Code

on:
  # טריגר ידני לבדיקה
  workflow_dispatch:

  # כל תגובה באישיו/ב־PR תפעיל
  issue_comment:
  pull_request_review_comment:

  # טריגר בדיקה: כל שינוי לקובץ ה־workflow
  push:
    paths:
      - ".github/workflows/claude.yml"

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Show event (debug)
        run: |
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          if [ -f "$GITHUB_EVENT_PATH" ]; then
            echo "---- event payload ----"
            cat "$GITHUB_EVENT_PATH" | head -c 2000
            echo -e "\n-----------------------"
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ github.token }}
